name: Green lady

on: 
  workflow_dispatch
  push:
    branches: [ main ]
  

jobs:
  build:
    runs-on: windows-latest
    steps:
       - uses: actions/setup-node@v3
       
       - name: Install dependencies
         run: npm ci
         
       - name: Build the app
         run: npm run build
         
       - name: Deploy 🚀
         uses: JamesIves/github-pages-deploy-action@v4
         with:
            folder: dist
    

  

  
